### ISSUE TITLE
Recommended Process

### ISSUE THREAD

**Issue by podworx** [rrirower/Channel-Feed-Manager#101]
Hi, Michael.

I believe I understand how the CFM works, for the most part.  Once I provide the initial feed, all updates are done to a .json file found within my Documents folder (/Channel Feed manager > Channels > Channel Feeds.

My questions is; how are people sharing this .json file with Roku?  Are people copying off their local computer and then placing it online somewhere?

And, same questions with the Search Feed generator.  Once *that* file is created (after validation), how is this file shared w/ Roku Developer's Search Feed section?

Thanks.

**Comment by rrirower** [comment]
The developer portal contains a location for you to specify your channel feed URL. I'm not sure about search feeds but I think you need to submit it for approval which implies you have it saved on a CDN somewhere with your channel feed.

**Comment by podworx** [comment]
I know the Roku Development environment for a channel allowed you to point to a feed url on Direct Publisher channels but that info is inside the .pkg's manifest file.  

Are you talking about a different "developer portal"?

**Comment by rrirower** [comment]
Sorry, no, I've been spending the day answering questions and writing code. My brain is a little foggy.

You are correct. Once you've stored your feed on a CDN, you just point to it from the manifest.

I would save the search feeds in the same location.

**Comment by podworx** [comment]
Yes, but the .json feed that is updated by your software sits on my _local_ computer.  How do folks systematically update the file that is being read by the .pkg, which has to be Internet-accessible?

**Comment by rrirower** [comment]
Your channel reads the contents of your feed file at start up. You've told it where the feed URL is in the manifest. It builds the UI based on your feed contents.

You've got two options. Update the feed file locally and re-upload it, or, develop a system that defects when you've made a new video available and updates the feed for you.

Most people choose to re-upload a new feed file.
