### ISSUE TITLE
Removing feed from library

### ISSUE THREAD

**Issue by adamesq** [rrirower/Channel-Feed-Manager#107]
**Describe the bug**
This is a minor one. I have a couple of lingering items in the Feed file library. One is the first feed I had tried (I think in version 1.0.05). The other is a settings file I accidentally brought in yesterday. When I delete, the item just...doesn't. For the former, I ended up going into the feeds folder and deleting the file to get the library to clear out (when I was on 1.0.05). That didn't work. Other feeds have easily deleted as expected. Just these two items...lingering. 

Double-clicking these items (as if I were trying to open them) gives me an error (expected), but they can't be removed.

**To Reproduce**
1. Not quite sure since it's only 2 items having an issue. 

**Expected behavior**
Items delete from feed library.

<img width="1006" alt="Screenshot 2023-10-03 at 9 51 04 AM" src="https://github.com/rrirower/Channel-Feed-Manager/assets/34196956/62f65e7a-b470-46df-8cd5-12bebfddf1a0">

**Comment by rrirower** [comment]
Can you post an image without the menu?
Have you possibly created 'orphans' by deleting files using Windows Explorer or some other mechanism prior to reporting this?

**Comment by adamesq** [comment]
For the first item, I _may_ have. (It was my first day using CFM). For the second, no. I inadvertently clicked on a setting file instead of importing a feed.

I ran into one other thing just a few minutes ago. I have one episode so far posted in a series. I don't get the option to either resume or restart the episode. It just resumes when selected. The option does still work for short videos. I know I saw the option under a 1.0.0.6 side load. One other thing...MY CHANNEL JUST SUCCESSFULLY PUBLISHED!🙏🏻 Sending a donation now...then going to post about it separately. THANK YOU, Michael. 

<img width="1006" alt="Screenshot 2023-10-03 at 10 22 07 AM" src="https://github.com/rrirower/Channel-Feed-Manager/assets/34196956/b0f36c6b-4eaf-4cea-a2bc-eab48b49b01e">

**Comment by adamesq** [comment]
I found a backup copy of that first legit feed (not the settings file) and put it back in the folder, restarted CFM and still can't delete the item from the feed file library. Perhaps once orphaned, aways orphaned?

**Comment by rrirower** [comment]
Can you zip up your "\Documents\Channel Feed Manager\Channels" folder and post it here?  I can try some quick code to check for and remove orphans.

**Comment by adamesq** [comment]
👍🏻 Attached. 
[Channel feeds.zip](https://github.com/rrirower/Channel-Feed-Manager/files/12795791/Channel.feeds.zip)

**Comment by rrirower** [comment]
Sorry, I need the zip to start in the Channels base folder:  I need everything in the image below.

![Capture](https://github.com/rrirower/Channel-Feed-Manager/assets/34550407/22fa46c1-f1dc-44bb-94c9-3c8cef4f561a)

**Comment by adamesq** [comment]
Sure!
[Channels.zip](https://github.com/rrirower/Channel-Feed-Manager/files/12796047/Channels.zip)

**Comment by rrirower** [comment]
You've got two orphans in your library.  I can craft something to clean that up.  I'll let you know when it's available.

**Comment by adamesq** [comment]
Thank you! No rush - if it's something I can do on my end (without screwing up CFM), happy to do it. You have really done a lot of support here!

**Comment by rrirower** [comment]
To remove 'orphan' feed files:

- Download the [Orhpan Channel Cleaner](https://github.com/rrirower/Channel-Feed-Manager/blob/main/ChannelOrphanCleaner.zip) to a new folder.
- Unzip the download file.
- Run the 'ChannelOrphanCleaner.exe' program.

**Comment by adamesq** [comment]
THANK YOU! Orphans have been removed.👏🏻👍🏻
