### ISSUE TITLE
When Changing URL of Episode In Series, URL Reverts (or doesn't save)

### ISSUE THREAD

**Issue by adamesq** [rrirower/Channel-Feed-Manager#108]
**Describe the bug**
I believe there is a bug with changing the URL of an episode in a series. 

**To Reproduce**
1. Go into a tv series.
2. Switch to episode tab
3. Change URL of the episode

**Expected behavior**
URL updates

**Actual behavior**
URL reverts back

**Additional context**
Seems to be a work-around if you delete the url, then add the new one, HOWEVER - must press enter, not just the save button.

**Comment by rrirower** [comment]
Are you double clicking on the URL field to edit it?  Do you then press the enter key to accept your change?

**Comment by adamesq** [comment]
Thought I did, but I can't reproduce it now! Sorry for the false alarm!
