### ISSUE TITLE
Error message when attempting to create Search Feed

### ISSUE THREAD

**Issue by rrirower** [rrirower/Channel-Feed-Manager#114]
### Discussed in https://github.com/rrirower/Channel-Feed-Manager/discussions/113

<div type='discussions-op-text'>

<sup>Originally posted by **podworx** October 23, 2023</sup>
When trying to create a search feed for a channel, each entry generates a FATAL message:

Program exception detected: 'The given key 'searchLicense' was not present in the dictounary.' in method 'AppendSearchFeed'.

Any thoughts on this, folks?</div>

**Comment by rrirower** [comment]
This is actually a bug in the installer.  The work around is the following:

1. Close CFM if open.

2. Navigate to C:\Users\xxxxx\AppData\Roaming\Channel Feed Manager.

3. Delete this file: _ChannelFeedManager.config_

4. Restart CFM.

**Comment by rrirower** [comment]
Is this still a problem for you?

**Comment by aaronmspelling** [comment]
it did solve my issue too - the search feed was validated and ingested 100%
thank you.

**Comment by podworx** [comment]
Yep, this worked for me as well.  Thanks!
