### ISSUE TITLE
Content Validation Error  - Search Feed

### ISSUE THREAD

**Issue by aaronmspelling** [rrirower/Channel-Feed-Manager#115]
Hi 
so 
search feed generated successfully 
the search feed validator validated the feed 
submitted the search feed  - it was validated in a couple of hours but in the validated content tab - 0% - downloaded the error log 

{"errors":[{"id":"CONTENT_ALL_PLAY_OPTIONS_REMOVED","issues":{"1002080":["All content.playOptions have been removed, causing the asset to be rejected. Please investigate other issues to determine what happened."],"1002079":["All content.playOptions have been removed, causing the asset to be rejected. Please investigate other issues to determine what happened."],"1000043":["All content.playOptions have been removed, causing the asset to be rejected. Please investigate other issues to determine what happened."],"1002078":["All content.playOptions have been removed, causing the asset to be rejected. Please investigate other issues to determine what happened."],"1002075":["All content.playOptions have been removed, causing the asset to be rejected. Please investigate other issues to determine what happened."],"1002074":["All content.playOptions have been removed, causing the asset to be rejected. Please investigate other issues to determine what happened."],"1002077":["All content.playOptions have been removed, causing the asset to be rejected. Please investigate other issues to determine what happened."],"1001890":["All content.playOptions have been removed, causing the asset to be rejected. Please investigate other issues to determine what happened."],"1002076":["All content.playOptions have been removed, causing the asset to be rejected. Please investigate other issues to determine what happened."],"1002082":["All content.playOptions have been removed, causing the asset to be rejected. Please investigate other issues to determine what happened."],"1002081":["All content.playOptions have been removed, causing the asset to be rejected. Please investigate other issues to determine what happened."],"1002073":["All content.playOptions have been removed, causing the asset to be rejected. Please investigate other issues to determine what happened."]}},{"id":"ASSET_REMOVED_CONTENT","issues":{"1002080":["Required field content has been removed. Please investigate other errors to determine what happened."],"1002079":["Required field content has been removed. Please investigate other errors to determine what happened."],"1000043":["Required field content has been removed. Please investigate other errors to determine what happened."],"1002078":["Required field content has been removed. Please investigate other errors to determine what happened."],"1002075":["Required field content has been removed. Please investigate other errors to determine what happened."],"1002074":["Required field content has been removed. Please investigate other errors to determine what happened."],"1002077":["Required field content has been removed. Please investigate other errors to determine what happened."],"1001890":["Required field content has been removed. Please investigate other errors to determine what happened."],"1002076":["Required field content has been removed. Please investigate other errors to determine what happened."],"1002082":["Required field content has been removed. Please investigate other errors to determine what happened."],"1002081":["Required field content has been removed. Please investigate other errors to determine what happened."],"1002073":["Required field content has been removed. Please investigate other errors to determine what happened."]}}],"warnings":[]}

I have only short-form  videos.

it looks like something is missing
any help would be appreciated

**Comment by rrirower** [comment]
I'll need the search feed the software generated and your json feed to investigate further.

**Comment by aaronmspelling** [comment]
Channel-Feed-Manager
[1_errors.json](https://github.com/rrirower/Channel-Feed-Manager/files/13238140/1_errors.json)
[15.json](https://github.com/rrirower/Channel-Feed-Manager/files/13238141/15.json)
[15Search.json](https://github.com/rrirower/Channel-Feed-Manager/files/13238142/15Search.json)

i added the error json Roku generated

thank you

**Comment by rrirower** [comment]
What software version are you using?  Version 1.0.0.7 introduced 'PlayOptions' for a Search feed.  Your search feed is missing these required fields.

**Comment by aaronmspelling** [comment]
1008
the latest
![Screenshot 11-02-2023 20 48 06](https://github.com/rrirower/Channel-Feed-Manager/assets/69145314/a8fb1393-8e48-4189-86e4-0e791a704e2d)

**Comment by rrirower** [comment]
Please try the resolution in issue #114 .  Let me know if this resolves your problem.

**Comment by rrirower** [comment]
Fixed by the steps in #114 .
