### ISSUE TITLE
search feed validation warning

### ISSUE THREAD

**Issue by aaronmspelling** [rrirower/Channel-Feed-Manager#118]
hi 
I submitted some feeds generated using the software 
all of them passed the first validation, but they had a warning that stopped the ingestion process.
PLAY_OPTION_AVAILABILITY_TIME_MISSING
I will attach the JSON feed and the search feed. 
When you have a little time, maybe you can look into it.
Thank you.
![lamont](https://github.com/rrirower/Channel-Feed-Manager/assets/69145314/e4020d49-1b62-43f7-b2dd-bf40c5f5fe42)
[WME.json](https://github.com/rrirower/Channel-Feed-Manager/files/13419986/WME.json)
[WMESearch.json](https://github.com/rrirower/Channel-Feed-Manager/files/13419987/WMESearch.json)

**Comment by rrirower** [comment]
The availability time fields are optional. Do you require them for your search feed?

**Comment by aaronmspelling** [comment]
I know those are optional, but ..... according to partner success, that is why they don't publish the feed. 
According to Kent Sandvik - the Roku guy working on the search feed on Roku's side- we should fix the warnings too -

**Comment by rrirower** [comment]
Ok. I'll look into it further.

**Comment by rrirower** [comment]
Can you provide your vanity code for the channel that fails to publish the search feed?  I'm in contact with partner success and they want your code for some reason.

**Comment by aaronmspelling** [comment]
of course
Vanity Access Code: [HGXNCKK](https://my.roku.com/account/add/HGXNCKK)
i am in contact with them as well.

**Comment by aaronmspelling** [comment]
I think that all this is way too new for them and they kind of try to see what's what,  in the partner's success. that is why I asked Kent about the errors and warnings -

**Comment by rrirower** [comment]
I think you may be right.  I was working with "Ryan" who indicated he couldn't look into it without your vanity code.  I went to Partner Success to provide the code and he had closed my activity.  He didn't give me a chance to reply.  I had to re-open the issue.

Pretty poor support...

**Comment by aaronmspelling** [comment]
waiting for Ryan ...

**Comment by rrirower** [comment]
Has this been resolved?

**Comment by aaronmspelling** [comment]
Holiday off time for Roku, so I didn't pressure it... I'll restart my "stressing" in January, but I will update you.
Thank you for following up.

**Comment by rrirower** [comment]
Any update?

**Comment by rrirower** [comment]
No user action.
