### ISSUE TITLE
When trying to add a live feed element, it is reporting that my thumbnail image is missing or incorrect. When I click on the eyeball, the thumbnail is clearly there. It will not let me add the element to the feed.

### ISSUE THREAD

**Issue by Lettybug333** [rrirower/Channel-Feed-Manager#126]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Screen Capture**
If you are able, please attach a screen capture(video) showing the problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by rrirower** [comment]
Can you please fill in the steps to reproduce the issue and other requested info?

**Comment by rrirower** [comment]
Please provide the URL for the thumbnail.

**Comment by rrirower** [comment]
No feedback from the user.  Closing.
