### ISSUE TITLE
Search feed language

### ISSUE THREAD

**Issue by aaronmspelling** [rrirower/Channel-Feed-Manager#153]
Hi
Ryan's lattes "stop" for our search feed was the language code for the videos.
In the search feed, the language is en-US - they said it should be en-us - all lowercase, or only en without any country code ......
the feed documentation 
https://developer.roku.com/en-gb/docs/specs/search/search-feed.md#multiregion-and-multilanguage-support
at some point 
	A list of languages in ISO 639-1 two-letter language code (lowercase) format for which the description is applicable.

And in the feed example, all are lowercase.
maybe you can look into it when you have a bit of time.

Thanks

**Comment by rrirower** [comment]
Thanks for following up on this. It will be fixed in the next version.
