### ISSUE TITLE
Won't open on my Windows 10 PC.

### ISSUE THREAD

**Issue by JLNjolo** [rrirower/Channel-Feed-Manager#159]
**What tool are you using?**
Channel Feed Manager

**Describe the bug**
The updated software is installed. The (your) icon appears on the toolbar at the bottom of my screen. When I double click to open your image appears on the screen but it vanishes quickly and nothing else happens. Then if I try again to open the software a notice appears that it is already open and I cannot open two instances of the software.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Screen Capture**
If you are able, please attach a screen capture(video) showing the problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by rrirower** [comment]
Are you using two monitors?

**Comment by JLNjolo** [comment]
No
________________________________

**Comment by rrirower** [comment]
I'm running version 1.0.1.2 and it opens without problems on Windows 10.  Have you tried uninstalling and re-installing?

**Comment by JLNjolo** [comment]
That worked. Thanks!
________________________________
