### ISSUE TITLE
Feed Manager needs to tell people where it is saving things!

### ISSUE THREAD

**Issue by jsonnentag** [rrirower/Channel-Feed-Manager#168]
This would seem like the most basic of concepts - tell the user WHERE the SAVED files are going to.

The only way I could figure anything out was buy looking in the Wiki and seeing there was a "Go to Export Folder" for when you are EXPORTING things and seeing that it went to this "general area" and then go back a directory or 2 and see there is a "Channel feeds" one.

Nothing should be that hidden and obscure. . . .

**Comment by jsonnentag** [comment]
C:\Users\THEOX\Documents\Channel Feed Manager\Channels\Channel feeds

**Comment by rrirower** [comment]
What are you exporting?

Export is only used if you are converting your feed file to another format.

**Comment by jsonnentag** [comment]
I'm not exporting anything.

I used "Add to your feed library" to import a JSON feed and it showed up fine in the "Feed file library". . . .

Fine, and just great! . . .  So exactly WHERE is the user to find that Feed file library and the location of all those files?  It isn't stated ANYWHERE (including the wiki - and nobody should have to look in a wiki to find where files being worked with are located anyway).

What I said is that the only way I could eventually find the location of the Feed file library was by seeing that there is a link in the "Export to external format. . ." tool window that says "Go to Export folder".  So then if you follow that link you get to the general location and can browse directory levels and find the location of the Feed file library.  All you get when you save the feed is a green window that says it was successful, nothing about where anything is.

At least in DP2SceneGraphWizard it does say when you save things that it is putting it on the Desktop (although I think it is a lot better to ask the user where they want to put it and just start out at some default location that they can then change if they feel like it).

**Comment by rrirower** [comment]
The Documents folder is a standard location on Windows for saving application files.  While I have not received any other complaints regarding this, I will update the Wiki to include the various file locations.

**Comment by rrirower** [comment]
The Wiki has been updated to show file locations.
