### ISSUE TITLE
Search feed Crash

### ISSUE THREAD

**Issue by DerekWongMI** [rrirower/Channel-Feed-Manager#182]
**What tool are you using?**
Channel Feed Manager 1.0.1.3

**Describe the bug**
Encounter fatal error when "Generate a search feed from this file"

**To Reproduce**
1. Go to 'Feed'
2. Click on 'Tools'
3. click on generate
4: Message appears "FATAL, Program exception detected:'The give key 'searchLicense' was not present in the dictionary.' in method 'AppendSearchFeed'.

**Screenshots**
![image](https://github.com/rrirower/Channel-Feed-Manager/assets/74847797/0cfccead-7173-490f-bbbe-65760800880e)

**Desktop (please complete the following information):**
 - OS: Win 11 Pro

** MORE
Also crashed when in Program Settings \ search feed \ Define Play Options, submitted a crash report then.

**Comment by rrirower** [comment]
Please attach your feed file so I can debug this error.

**Comment by DerekWongMI** [comment]
Thank you, and I have shortened the json for convenience.
 
[example.json](https://github.com/rrirower/Channel-Feed-Manager/files/15112624/example.json)

**Comment by DerekWongMI** [comment]
I also want to add for the 2nd problem  Settings \ search feed \ Define Play Options it crash, it does not matter even if the json is new and empty, its any time I click the button.

**Comment by rrirower** [comment]
Are you saying the system crashes when you click the "Display play options..." button?

**Comment by rrirower** [comment]
I think you may have a mismatch in the code you installed.  Can you uninstall the current version and reinstall it?

**Comment by rrirower** [comment]
Also, please try the resolution in "Error message when attempting to create Search Feed" #114

**Comment by DerekWongMI** [comment]
I went ahead and deleted everything in C:\Users\xxxxx\AppData\Roaming\Channel Feed Manager, and then deleted everything in C:\Users\xxxxxxxxxx\Documents\Channel Feed Manager . Uninstalled the program, restarted the computer and reinstalled the program. Started the program it gave me a message on "fatal error, "something missing"(can't remember the rest)", BUT, if i click OK enough times to get pass that, the program will open, both issues mentioned above will be gone, and it will be able to open the program again with no issue. Thank you.
