### ISSUE TITLE
Search feed error

### ISSUE THREAD

**Issue by wajidbux** [rrirower/Channel-Feed-Manager#186]
Channel feed manager- latest version

Search feed fails metadata validation.

![image](https://github.com/rrirower/Channel-Feed-Manager/assets/54876296/51156305-c26f-4354-a2c6-9ea6b029902f)

Play option availability time ( Validity ) is not generated in the .json feed file or .json search feed-
feed file link- https://hookup.dreamhosters.com/roku1.json
search feed link - https://api.npoint.io/539e58461f8707a4bb79

Missing rating source as per Roku search feed documentation-
1.  Australian Classification Board ( ACB )
2.  General Directorate of Radio, Television and Film ( RTC )

**Comment by rrirower** [comment]
Please use the bug report when reporting an issue. 

What version are you using?

**Comment by wajidbux** [comment]
version 1.0.1.3

**Comment by rrirower** [comment]
Both links you posted are for a Search feed.  Please post your feed file url.

**Comment by wajidbux** [comment]
feed file link- https://hookup.dreamhosters.com/roku.json

**Comment by rrirower** [comment]
Those two rating sources are missing from the DP JSON spec.  Hence, tat's why they are missing in Channel Feed Manager.  They will be added.

**Comment by wajidbux** [comment]
ok, thanks

**Comment by rrirower** [comment]
A quick review of your feed file shows that you do not have any 'validityPeriod' fields.  Did you mean to specify them in the feed file?  They are optional in the feed file and the Search feed.

**Comment by wajidbux** [comment]
I have the validity periods but it just does not show up on the feed file, it does not generate

![image](https://github.com/rrirower/Channel-Feed-Manager/assets/54876296/85ca0bb2-1893-450a-a00b-f0a2e5a2989a)

**Comment by wajidbux** [comment]
I agree that the validity period is optional but the meta-data validation fails during search feed validation.

**Comment by rrirower** [comment]
I added a rating and source to your feed file and it saved it correctly.
![Capture](https://github.com/rrirower/Channel-Feed-Manager/assets/34550407/6985b983-a43e-41a0-a5eb-3a0d77620704)
It shows up when I close and reopen CFM.  Are you saving the feed file contents when you make a change?

**Comment by rrirower** [comment]
Sorry, I did not look for validty fields.  Will check now.

**Comment by wajidbux** [comment]
ok

**Comment by rrirower** [comment]
I think I see the problem with the validity dates not making it to the search feed, but, I'll need to dig deeper.

**Comment by rrirower** [comment]
I've corrected the Rating and Availability time stamp issues.  The fix will be in the next release.

**Comment by wajidbux** [comment]
Thank you.

**Comment by rrirower** [comment]
Resolved in version [1.0.1.4](https://github.com/rrirower/Channel-Feed-Manager/releases/tag/1.0.1.4).
