### ISSUE TITLE
Startup message

### ISSUE THREAD

**Issue by rain-dotcom** [rrirower/Channel-Feed-Manager#201]
![Annotation 2024-06-21 175525](https://github.com/rrirower/Channel-Feed-Manager/assets/172065401/334bd959-2bf1-4d2c-a406-1fd02118d73b)

the software show this

**Comment by rrirower** [comment]
That message means you are trying to start the software and it is already running. It is not an error.

**Comment by rain-dotcom** [comment]
oh ok 
but the software did not show again

**Comment by rrirower** [comment]
Try rebooting your machine and restarting the software.

**Comment by rain-dotcom** [comment]
It appears i get the error when i start the software.
![Annotation 2024-06-22 180604](https://github.com/rrirower/Channel-Feed-Manager/assets/172065401/35c3b905-2628-4179-a329-f76611ff6c2c)
.

**Comment by rain-dotcom** [comment]
why the software is working on my laptop

**Comment by rrirower** [comment]
Please read the software [prerequisites](https://github.com/rrirower/Channel-Feed-Manager#prerequisites) to make sure you meet those requirements.  Then, uninstall the software and reinstall.

**Comment by rain-dotcom** [comment]
![WhatsApp Image 2024-06-23 at 12 36 30_4b23c250](https://github.com/rrirower/Channel-Feed-Manager/assets/172065401/26d3531b-3af1-4396-a009-2ca9bc8b90a8)

hello i have upload my video to the software but how can i copy feed link to my roku channel

**Comment by rrirower** [comment]
Please refer to the [Wiki](https://github.com/rrirower/Channel-Feed-Manager/wiki/Where-are-my-files%3F).  It details where you can find your feed files.  Then upload the feed file to a Content Delivery Network (CDN) like Amazon S3, or similar.  After that, generate your channel package specifying the URL of the feed file you uploaded to the CDN.

**Comment by rrirower** [comment]
This is not a problem with the Channel Feed Manager.  The errors you show are related to the DP2SceneGraphWizard project.  You should reply in the appropriate project.

Browse through the Discussions in the DP2SceneGraphWizard project.  In particular, look at discussion [#38](https://github.com/rrirower/DP2SceneGraphWizard/discussions/38).  Also, search out some of @ferdiworks excellent replies to similar discussions.

**Comment by ferdiworks** [comment]
@rain-dotcom I looked at yiour image!
You past #1 Performance = Good!
You got Error on #2 Deep Linking - Did you do the deep linking on Roku and add at least one video link to deep Link?
You got Error on #3 Video Playback - Please note that your feed you sent me showed you used Vimeo, Vimeo and Vimeo no longer supports OTT or CTV platforms and doesn't offer unlimited Bandwith! Although some still use Vimeo they do not offer speed or premium play benefits so you may have a playback issue here and there!
#5 you should ensure you added a scxreen saver image to your account in Roku or in your package!

**Comment by rain-dotcom** [comment]
[ferdiworks](https://github.com/ferdiworks)

Thank you 
i find the error and i fix it
the problem is not with my feed url
the problem is with deep link i Add i have fix the error and my channel is working now
