### ISSUE TITLE
Import from External File error

### ISSUE THREAD

**Issue by kerednekt1a** [rrirower/Channel-Feed-Manager#202]
**What tool are you using?**
Channel Feed Manager

**Please attach your feed file to this issue for testing.**
[mmvc.json](https://github.com/user-attachments/files/15935732/mmvc.json)
[MY_MUSIC_VIDEO_CHANNEL.csv](https://github.com/user-attachments/files/15935733/MY_MUSIC_VIDEO_CHANNEL.csv)

**Describe the bug**
On importing an external file (csv file) I get the error
"Failure

Program exception detected: 'Exception has been thrown by the target of an invocation. in method runinit with target '"
See screenshot.

**To Reproduce**
1. Go to Tools>Import from external source
2. Click on 1.Select external file you'd like to import then '....', csv chosen from my PC directory
3. Scroll down to Select an importer to load your file '....', "Imports csv files into MRSS, clicked on Import
Failure

Program exception detected: 'Exception has been thrown by the target of an invocation. in method runinit with target '"

**Expected behavior**
My csv file is based on the CSVTEMPLATE.csv
in the Channel Feed Manager /Importers directory
[CSVTEMPLATE.csv](https://github.com/user-attachments/files/15935802/CSVTEMPLATE.csv)

I expected file to beomported and record added to the data feed.
**Screenshots**
![cfm-import-error](https://github.com/rrirower/Channel-Feed-Manager/assets/154466498/788241b5-cf6b-4068-a5c1-576405f5f2b7)

**Screen Capture**
If you are able, please attach a screen capture(video) showing the problem.

**Desktop (please complete the following information):**
 - OS: WIN 10

**Additional context**

**Comment by rrirower** [comment]
Thank you for submitting a clear issue report.

**Comment by rrirower** [comment]
`CSVTEMPLATE.csv` is not a file that I install.  Your csv file is not in the correct format.  Please look at the `Csv2Mrss.csv` file in the ..\Documents\Channel Feed Manager\Importers folder for a sample of the accepted format.

I'll add an entry to the Wiki to explain the format.

**Comment by rrirower** [comment]
Wiki has been updated.

**Comment by kerednekt1a** [comment]
Many thanks for your speedy reponse..
Indeed the CSVTEMPLATE.csv file was my file of how I had (incorrectly)
interpreted your Csv2Mrss.csv file.
Your Wiki update made it clearer.
Thanks again.
Derek
