### ISSUE TITLE
Search feed not generating

### ISSUE THREAD

**Issue by wajidbux** [rrirower/Channel-Feed-Manager#215]
Channel Feed Manager Version 1.0.1.5

The search feed is not getting generated, the error message is shown below. 
And when I roll back to the previous version it works well.

![Screenshot 2024-09-01 151040](https://github.com/user-attachments/assets/fb2cf4a1-2c0a-431a-8bd5-748d02a3bdb5)

**Comment by wajidbux** [comment]
And when I roll back to the previous version it works well.

**Comment by rrirower** [comment]
Please attach the feed file that shows this error.

**Comment by wajidbux** [comment]
feed file- https://cinematineeroku.dreamhosters.com/roku.json
 
but to test it better you can remove all the search feeds from your folder and try generating it once again using the latest feed manager

**Comment by rrirower** [comment]
This is a bug that was introduced in the latest version.  It will be fixed in the next.

**Comment by wajidbux** [comment]
Hi Michael, the software needs to be updated immediately, it crashed on opening when I re-installed it, and I got the error as shown below-

![Screenshot 2024-09-13 162444](https://github.com/user-attachments/assets/3096e15d-39be-4b1e-be6b-eaa7f3103966)

**Comment by rrirower** [comment]
Ok.  I'll try to expedite it.

**Comment by rrirower** [comment]
This should now be resolved in the latest version 1.0.1.6.
