### ISSUE TITLE
Search feed not generating

### ISSUE THREAD

**Issue by wajidbux** [rrirower/Channel-Feed-Manager#224]
Channel Feed Manager 1.0.1.6

Search feeds for new channels are not being generated. When adding a new channel and content, on clicking the generate search feed option the green dialogue box appears but when going to the search folder there is no file. I am attaching the feed file for your reference.

[Untitled demo.json](https://github.com/user-attachments/files/17213022/Untitled.demo.json)

**Comment by rrirower** [comment]
This is not a bug.  The code uses the internal 'provider name' as the external file name for the Search feed.  Your file is saved as 'Movieland TV Search.json'.
