### ISSUE TITLE
Corrupts feed and crashes constantly

### ISSUE THREAD

**Issue by Gaalen69** [rrirower/Channel-Feed-Manager#67]
Creating a series roku feed with seasons and episodes. During the process, the dropdown menu for creating new episodes and/or seasons only shows the existing seasons/episodes, no add new or delete choice. Usually before this happens, the seasons dropdown doubles up, showing the existing seasons and add/delete options twice. From that point onward, I can't add or delete data. The feed is immutable. Sometimes after this occurs I get a fatal exception error and the program closes. I've tried saving the content, going back to the main screen and re-entering the feed, as well as shutting the program down and reopening it. The add/delete options no longer appear. I've deleted the feed and re-entered from scratch with the same results. I've saved constantly, I've even didn't save the content to see if that made a difference. All with the same result. What am I doing wrong?

**To Reproduce**
1. Create roku feed
2. Create series with Seasons and Episodes
3. Create first season and add episodes
4. Create second season and add episodes
5. See error

**Expected behavior**
Not sure what this means

**Screenshots**

**Screen Capture**
Don't have one now, but can try later, just need to take a break as I had to recreate the feed three times already today to only have it go sideways

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 64 gig dram
 - AMD Threadripper

**Additional context**
No additional content at the moment

**Comment by rrirower** [comment]
I've received your issue and will look into it.  Be advised that the software does have automatic backup, so, you shouldn't lose anything.

**Comment by rrirower** [comment]
Related to issue #66 .

**Comment by rrirower** [comment]
I followed the steps you provided and could not generate the error.  Are you using a prior existing feed file?  If so, can you attach it here?

If possible, please attach a screen capture, or, screen snips of the steps and/or error.

**Comment by Gaalen69** [comment]
I appreciate you following it up. It did it again. This time I saved the
entire feed after every episode entry but when I attempted to add the
second episode of the second season, I got the same error where the add new
episode/delete episode, disappeared from the dropdown list. I created a
feed from scratch using your software, no import. Here is a screen capture
of the latest incident and a copy of the feed file that was created. Help!
Don't want to do all this manually, but will if its my only option. Thanks!

**Comment by rrirower** [comment]
You should not have to do it manually if I can track down the steps you are using.  However, there are no files attached to this issue.

**Comment by Gaalen69** [comment]
My apologies, I responded to your email directly and the attached files never made it through. Responding through GitHub. Here are the files I spoke of earlier and all the log files I have. Thanks!
[2023-06-29ChannelFeedManager.txt](https://github.com/rrirower/Channel-Feed-Manager/files/11952206/2023-06-29ChannelFeedManager.txt)
[2023-06-30ChannelFeedManager.txt](https://github.com/rrirower/Channel-Feed-Manager/files/11952207/2023-06-30ChannelFeedManager.txt)
[2023-07-04ChannelFeedManager.txt](https://github.com/rrirower/Channel-Feed-Manager/files/11952208/2023-07-04ChannelFeedManager.txt)
![Roku Feed Error](https://github.com/rr
[Nation Extreme Wrestling Search JSON file.txt](https://github.com/rrirower/Channel-Feed-Manager/files/11952216/Nation.Extreme.Wrestling.Search.JSON.file.txt)
irower/Channel-Feed-Manager/assets/86689420/88f0b0bd-3ba9-47ee-a6ae-6d8ad223dc42)

**Comment by Gaalen69** [comment]
![Roku Feed Error](https://github.com/rrirower/Channel-Feed-Manager/assets/86689420/159e3941-ee3a-46e3-9d9c-9f80e72bf1d9)

**Comment by Gaalen69** [comment]
I was just looking over the json feed file that the program generated and it doesn't seem to contain any of the source urls I saved. Did I do something wrong?

**Comment by rrirower** [comment]
I'm a bit confused.  The JSON file you attached (Nation Extreme Wrestling Search JSON file.txt) is a Search file and not a feed file.  Was that intentional?

**Comment by Gaalen69** [comment]
My apologies, I am new to this. Here is the feed file. Thanks!
[Nation Extreme Wrestling Feed.txt](https://github.com/rrirower/Channel-Feed-Manager/files/11952491/Nation.Extreme.Wrestling.Feed.txt)

**Comment by rrirower** [comment]
Thanks. I'll take a closer look.

**Comment by rrirower** [comment]
I attached a screen capture for you to review.  Your feed file opens successfully and I see the required items in the dropdown menus.  If at all possible, it would help greatly if you can document your steps with a screen capture.  If that's not possible, please write down the steps in detail.  I know you listed them earlier, but, it's just a brief overview.  I need to know the exact steps you take in order to try and recreate the problem.  You may have come across a condition that only you've been able to find.  I need to try and narrow down what steps create that condition that allows the error you see.

https://github.com/rrirower/Channel-Feed-Manager/assets/34550407/2f7ea93c-3f15-4efe-88d2-1b7466fad086

**Comment by rrirower** [comment]
After testing some more, I think I stumbled on your problem.  I need to test it further.  Hold off on sending me anything.

**Comment by Gaalen69** [comment]
Awesome, thanks!

**Comment by rrirower** [comment]
I believe I've found the bug and will have a fix available this weekend.

**Comment by Gaalen69** [comment]
Awesome, thanks!

**Comment by rrirower** [comment]
Fixed in version 1.0.0.4.
