### ISSUE TITLE
[New Feature Request] Channel listing

### ISSUE THREAD

**Issue by aaronmspelling** [rrirower/Channel-Feed-Manager#70]
not really a problem but ....
when you open the feed manager all your channels are listed under the Open recent channel/feed file library 
al the channels are listed by Developer
when you manage more then 3 channels :) it is hard to open every feed to see if it is the channel you want to work on or not
maybe you could add a channel title to the list - so we know what channel to choose.
:) 

thanks

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by rrirower** [comment]
I will take a look at this and comment later.

**Comment by aaronmspelling** [comment]
thank you

**Comment by rrirower** [comment]
I've updated the code today to include a title in the listing.  I should be able to post a new version this weekend.

**Comment by rrirower** [comment]
Added in version 1.0.0.6

**Comment by aaronmspelling** [comment]
what is the right way to update your software?

**Comment by rrirower** [comment]
You'll need to download the installer from GitHub. I've run into some problems trying to use GitHub as an update server. I will be abandoning it in the next release.

Did you get a service message explaining this when you tried to update?

**Comment by aaronmspelling** [comment]
i didn't try yet - downloaded the new zip and  - well better ask :) 
uninstall the old and install the new or just install the new version over the new :)

**Comment by rrirower** [comment]
Did you start the older version and see an update message followed by a service message?

You should be able to install 1.0.0.6 over the top of your existing setup.

**Comment by aaronmspelling** [comment]
it worked perfectly - just installed it over the previous version
