### ISSUE TITLE
Roku Search Feed

### ISSUE THREAD

**Issue by aaronmspelling** [rrirower/Channel-Feed-Manager#71]
I was delighted to see you have a Roku search feed generator. 
Unfortunately, it is not working.
Any plans for improving it? 

Now that Roku has automated the search feed submissions for SDK channels - it could come in very handy for many users.

The following errors and warnings were encountered:
[
  {
    "id": "1000452",
    "errors": [
      "All images have been removed. An asset must have at least one image. Please investigate other errors to determine what happened.",
      "All content.playOptions have been removed, causing the asset to be rejected. Please investigate other issues to determine what happened.",
      "Required genres array is missing",
      "Required field content has been removed. Please investigate other errors to determine what happened."
    ],
    "warnings": [
      "Required field image.url is missing",
      "Required field image.type is missing",
      "The playOption had all availabilityInfo.country removed",
      "The shortDescription and longDescription array contains multiple items with the same normalized language (en-US) and same value. Descriptions should be unique",
      "The provided advisoryRating.value UNRATED is not valid for source BBFC. Valid values for this rating source are [12A, 12, 12-A, 15, U, PG, 18, R-18, R18]. Rating will be removed.",
      "Required field playOption.availabilityInfo is missing or removed. This content will not be available in any region",
      "The playOption availability time is missing or removed. This content will be available indefinitely",
      "The provided value for field playOption.availabilityInfo.country en-US is not valid. Please use one of the following values: [de, hn, fr, bo, br, gb, ie, ca, ec, us, sv, cl, mx, co, gt, es, cr, skyuk, ar, pa, at, au, pe, skyie, ni]"
    ]
  },

**Comment by rrirower** [comment]
I'll need the feed file that was used to generate the errors. I should be able to debug the code using the requested feed file.

**Comment by aaronmspelling** [comment]
[Eczema Fix.zip](https://github.com/rrirower/Channel-Feed-Manager/files/12248060/Eczema.Fix.zip)
 i put in a zip the json and the resulted search feed

thank you

**Comment by rrirower** [comment]
I believe I found the bug and should be able to fix it.  I'll report back when it's fixed.

**Comment by aaronmspelling** [comment]
thank you

**Comment by rrirower** [comment]
Resolved in version 1.0.0.6
