### ISSUE TITLE
Wiki display after install

### ISSUE THREAD

**Issue by rrirower** [rrirower/Channel-Feed-Manager#83]
Hello 
i installed This [Channel Feed Manager software](https://github.com/rrirower/Channel-Feed-Manager) After installing and click finish it take me to this page
please what is the next step to take
![Annotation 2023-08-08 182714](https://github.com/rrirower/Channel-Feed-Manager/assets/141790541/9cd5712b-97f2-42a0-8da7-ce2061d1ad40)

_Originally posted by @Ramadeli in https://github.com/rrirower/Channel-Feed-Manager/issues/76#issuecomment-1670492972_

**Comment by fronderblash** [comment]
How can we run the installed software.?

**Comment by rrirower** [comment]
No response from the user.
